#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: no
  tasks:
    - name: create an initial database
      mysql_db:
        login_host: ::1
        name: ansible-playbook-example
        state: present
      register: dbstatus

    - name: import a database scheme
      mysql_db:
        login_host: ::1
        name: ansible-playbook-example
        state: import
        target: ansible-playbook-example.sql
      # could be done with a handler, but we need the database for subsequent tasks
      when: dbstatus.changed

    - name: update a row
      mysql_query:
        name: ansible-playbook-example
        table: simple_table
        login_host: ::1
        login_user: root
        login_password: password
        identifiers:
          identifier1: 4
          identifier2: 'eight'
        values:
          value1: 16
          value2: 'sixteen plus 1'
        defaults:
          default1: can be anything, will be ignored for update
          default2: will not change

    - name: insert a row
      mysql_query:
        name: ansible-playbook-example
        table: simple_table
        login_host: ::1
        login_user: root
        login_password: password
        identifiers:
          identifier1: 14
          identifier2: 'eighteen'
        values:
          value1: 115
          value2: 'one-hundred-sixteen'
        defaults:
          default1: 125
          default2: one-hundred-25
